name: Hoyolab Auto Check-in

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3' 

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      env:
        COOKIE: ${{ secrets.COOKIE }}
        USER_AGENT: ${{ secrets.USER_AGENT }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        python main.py
